builder: mediacloud

corpus:
  base_dir: corpora/air_quality/china

parameters:
  queries:
    - '("air pollution" OR "air quality" OR "空气污染" OR "空气质量")'
  collections:
    - id: 34412193
      name: China - National
  date_from: 2025-01-01
  date_to: today
  rate_limit:
    requests_per_minute: 3
    min_interval: 20.0
    enabled: true

extra_meta:
  country_iso3: CHN
  comment: National air quality corpus for China
  topic: air_quality


