builder: mediacloud

corpus:
  base_dir: corpora/air_quality/india

parameters:
  queries:
    - '("air pollution" OR "air quality" OR "वायु प्रदूषण" OR "वायु गुणवत्ता")'
  collections:
    - id: 34412118
      name: India - National
  date_from: 2025-07-13
  date_to: today
  rate_limit:
    requests_per_minute: 3
    min_interval: 20.0
    enabled: true

extra_meta:
  country_iso3: IND
  comment: National air quality corpus for India
  topic: air_quality


