builder: mediacloud

corpus:
  base_dir: corpora/air_quality/pakistan

parameters:
  queries:
    - '("air pollution" OR "air quality" OR "ہوا کی آلودگی" OR "ہوا کے معیار")'
  collections:
    - id: 34412272
      name: Pakistan - National
  date_from: 2025-07-13
  date_to: today
  rate_limit:
    requests_per_minute: 3
    min_interval: 20.0
    enabled: true

extra_meta:
  country_iso3: PAK
  comment: National air quality corpus for Pakistan
  topic: air_quality


