builder: mediacloud

corpus:
  base_dir: corpora/air_quality/south_africa

parameters:
  queries:
    - '("air pollution" OR "air quality" OR "lugbesoedeling" OR "lugkwaliteit" OR "umoya ongcolile" OR "ikhwalithi yomoya")'
  collections:
    - id: 34412238
      name: South Africa - National
  date_from: 2025-07-13
  date_to: today
  rate_limit:
    requests_per_minute: 3
    min_interval: 20.0
    enabled: true

extra_meta:
  country_iso3: ZAF
  comment: National air quality corpus for South Africa
  topic: air_quality


