[project]
name = "efi-corpus"
version = "0.1.0"
description = "Local corpus building framework with MediaCloud integration"
authors = [
    {name = "HT"}
]
readme = "README.md"
requires-python = "^3.10"
dependencies = [
    "zstandard (>=0.23.0,<0.24.0)",
    "requests (>=2.32.4,<3.0.0)",
    "python-decouple (>=3.8,<4.0)",
    "mediacloud (>=4.4.1,<5.0.0)",
    "beautifulsoup4 (>=4.13.4,<5.0.0)",
    "newspaper3k (>=0.2.8,<0.3.0)",
    "lxml[html-clean] (>=6.0.0,<7.0.0)"
]

[project.optional-dependencies]
dev = [
    "pytest>=8.4.1",
    "pytest-mock>=3.14.1"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = "-v --tb=short"

