[tool.poetry]
name = "efi-corpus"
version = "0.1.0"
description = "EFI Corpus Building and Analysis Tools"
authors = ["Your Name <your.email@example.com>"]
readme = "README.md"
packages = [
    {include = "efi_corpus"},
    {include = "efi_analyser"},
    {include = "efi_findings"}
]

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.31.0"
zstandard = "^0.22.0"
newspaper3k = "^0.2.8"
beautifulsoup4 = "^4.12.0"
mediacloud = "^4.0.0"
pyyaml = "^6.0.1"
openai = "^1.0.0"
PyPDF2 = "^3.0.0"
python-dotenv = "^1.1.1"

[tool.poetry.group.analysis]
optional = true

[tool.poetry.group.analysis.dependencies]
sentence-transformers = "^2.2.0"
scikit-learn = "^1.3.0"
numpy = "^1.24.0"
pandas = "^2.0.0"
matplotlib = "^3.7.0"
seaborn = "^0.12.0"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = "-v --tb=short"

