builder: mediacloud

corpus:
  base_dir: corpora/mediacloud_india_airquality

parameters:
  keywords:
    en: ["air pollution", "air quality", "PM2.5", "PM 2.5", "PM10", "PM 10", "particulate matter", "smog", "haze", "clean air", "air quality index", "air quality rating", "air quality score", "air quality forecast", "air quality warning", "air quality alert"]
    hi: ["वायु प्रदूषण", "वायु गुणवत्ता", "पीएम 2.5", "पीएम 10", "कण पदार्थ", "धुंध", "कुहासा", "स्वच्छ वायु", "स्वच्छ हवा"]
  collections:
    - id: 34412118
      name: India - National
  date_from: 2025-06-01
  date_to: today
  rate_limit:
    requests_per_minute: 3
    min_interval: 20.0
    enabled: true
  domain_blacklist:
    - "livemint.com"
    - "latest.inkhabar.com"  # Already failing in your corpus build
  url_blacklist:
    - "weather-today-aqi-and-rain-forecast"  # Exclude weather forecast URLs

extra_meta:
  country_iso3: IND
  comment: National air quality corpus for India
  topic: air_quality
  max_stories: 1000


